### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa-gui#27]
![](https://user-images.githubusercontent.com/7553998/29546358-8b91cff4-8726-11e7-8a8a-90a591902658.png)

```
22733 verbose unbuild rmStuff nowa-build@1.18.0 from /Users/wy/.nowa-gui/installation/node_modules
22734 info lifecycle nowa-build@1.18.0~postuninstall: nowa-build@1.18.0
22735 silly unbuild file-loader@0.9.0
22736 info lifecycle file-loader@0.9.0~preuninstall: file-loader@0.9.0
22737 info lifecycle file-loader@0.9.0~uninstall: file-loader@0.9.0
22738 verbose unbuild rmStuff file-loader@0.9.0 from /Users/wy/.nowa-gui/installation/node_modules
22739 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/url-loader/node_modules
22740 info lifecycle file-loader@0.9.0~postuninstall: file-loader@0.9.0
22741 silly unbuild stylus@0.54.5
22742 info lifecycle stylus@0.54.5~preuninstall: stylus@0.54.5
22743 info lifecycle stylus@0.54.5~uninstall: stylus@0.54.5
22744 verbose unbuild rmStuff stylus@0.54.5 from /Users/wy/.nowa-gui/installation/node_modules
22745 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/stylus-loader/node_modules
22746 silly gentlyRm parent.path = /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/stylus-loader/node_modules/stylus
22747 silly gentlyRm parent.managed = false
22748 silly gentlyRm target.path =  /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/stylus-loader/node_modules/.bin/stylus
22749 silly gentlyRm target.symlink = ../../../_stylus@0.54.5@stylus/bin/stylus
22750 silly gentlyRm target.managed = false
22751 silly gentlyRm target.inParent =  false
22752 info gentlyRm /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/stylus-loader/node_modules/stylus is not contained in any diretory npm is known to control or any place they link to
22753 silly unbuild less@2.7.2
22754 info lifecycle less@2.7.2~preuninstall: less@2.7.2
22755 info lifecycle less@2.7.2~uninstall: less@2.7.2
22756 verbose unbuild rmStuff less@2.7.2 from /Users/wy/.nowa-gui/installation/node_modules
22757 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/less-loader/node_modules
22758 silly gentlyRm parent.path = /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/less-loader/node_modules/less
22759 silly gentlyRm parent.managed = false
22760 silly gentlyRm target.path =  /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/less-loader/node_modules/.bin/lessc
22761 silly gentlyRm target.symlink = ../../../_less@2.7.2@less/bin/lessc
22762 silly gentlyRm target.managed = false
22763 silly gentlyRm target.inParent =  false
22764 info gentlyRm /Users/wy/.nowa-gui/installation/node_modules/nowa-server/node_modules/less-loader/node_modules/less is not contained in any diretory npm is known to control or any place they link to
22765 silly unbuild webpack@1.13.3
22766 info lifecycle webpack@1.13.3~preuninstall: webpack@1.13.3
22767 info lifecycle webpack@1.13.3~uninstall: webpack@1.13.3
22768 verbose unbuild rmStuff webpack@1.13.3 from /Users/wy/.nowa-gui/installation/node_modules
22769 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-lib/node_modules/babel-loader/node_modules
22770 silly gentlyRm parent.path = /Users/wy/.nowa-gui/installation/node_modules/nowa-lib/node_modules/babel-loader/node_modules/webpack
22771 silly gentlyRm parent.managed = false
22772 silly gentlyRm target.path =  /Users/wy/.nowa-gui/installation/node_modules/nowa-lib/node_modules/babel-loader/node_modules/.bin/webpack
22773 silly gentlyRm target.symlink = ../../../_webpack@1.13.3@webpack/bin/webpack.js
22774 silly gentlyRm target.managed = false
22775 silly gentlyRm target.inParent =  false
22776 info gentlyRm /Users/wy/.nowa-gui/installation/node_modules/nowa-lib/node_modules/babel-loader/node_modules/webpack is not contained in any diretory npm is known to control or any place they link to
22777 silly unbuild babel-core@6.14.0
22778 info lifecycle babel-core@6.14.0~preuninstall: babel-core@6.14.0
22779 info lifecycle babel-core@6.14.0~uninstall: babel-core@6.14.0
22780 verbose unbuild rmStuff babel-core@6.14.0 from /Users/wy/.nowa-gui/installation/node_modules
22781 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-lib/node_modules/babel-loader/node_modules
22782 info lifecycle babel-core@6.14.0~postuninstall: babel-core@6.14.0
22783 silly unbuild mkdirp@0.5.1
22784 info lifecycle mkdirp@0.5.1~preuninstall: mkdirp@0.5.1
22785 info lifecycle mkdirp@0.5.1~uninstall: mkdirp@0.5.1
22786 verbose unbuild rmStuff mkdirp@0.5.1 from /Users/wy/.nowa-gui/installation/node_modules
22787 verbose unbuild rmStuff in /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules
22788 silly gentlyRm parent.path = /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/mkdirp
22789 silly gentlyRm parent.managed = false
22790 silly gentlyRm target.path =  /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/.bin/mkdirp
22791 silly gentlyRm target.symlink = ../../../_mkdirp@0.5.1@mkdirp/bin/cmd.js
22792 silly gentlyRm target.managed = false
22793 silly gentlyRm target.inParent =  false
22794 info gentlyRm /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/mkdirp is not contained in any diretory npm is known to control or any place they link to
22795 verbose unlock done using /Users/wy/.npm/_locks/staging-d1d60b02c1751a0b.lock for /Users/wy/.nowa-gui/installation/node_modules/.staging
22796 warn enoent ENOENT: no such file or directory, open '/Users/wy/.nowa-gui/installation/package.json'
22797 verbose enoent This is related to npm not being able to find a file.
22798 warn react-dom@15.6.1 requires a peer of react@^15.6.1 but none was installed.
22799 warn installation No description
22800 warn installation No repository field.
22801 warn installation No README data
22802 warn installation No license field.
22803 verbose stack Error: Refusing to delete /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/.bin/mkdirp: containing path /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/mkdirp isn't under npm's control
22803 verbose stack     at clobberFail (/Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/lib/utils/gently-rm.js:151:12)
22803 verbose stack     at isSafeToRm (/Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/lib/utils/gently-rm.js:111:15)
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/lib/utils/gently-rm.js:84:5
22803 verbose stack     at LOOP (/Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/slide/lib/chain.js:18:7
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/lib/utils/gently-rm.js:204:16
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/iferr/index.js:13:50
22803 verbose stack     at cb (/Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/lib/utils/gently-rm.js:181:16
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/iferr/index.js:11:16
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/iferr/index.js:11:16
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/iferr/index.js:11:16
22803 verbose stack     at /Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
22803 verbose stack     at FSReqWrap.oncomplete (fs.js:112:15)
22804 verbose cwd /Users/wy/.nowa-gui/installation
22805 verbose Darwin 16.5.0
22806 verbose argv "/Applications/NowaGUI.app/Contents/Frameworks/NowaGUI Helper.app/Contents/MacOS/NowaGUI Helper" "/Applications/NowaGUI.app/Contents/Resources/app/node_modules/npm/bin/npm-cli.js" "install" "nowa-build@^1" "-S" "--no-optional" "-registry=http://registry.npm.taobao.org" "-loglevel=warn" "--scripts-prepend-node-path=auto"
22807 verbose node v7.4.0
22808 verbose npm  v5.3.0
22809 error path /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/.bin/mkdirp
22810 error code EEXIST
22811 error Refusing to delete /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/.bin/mkdirp: containing path /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/mkdirp isn't under npm's control
22812 error File exists: /Users/wy/.nowa-gui/installation/node_modules/nowa-build/node_modules/.bin/mkdirp
22813 error Move it away, and try again.
22814 verbose exit [ 1, true ]
```

**Comment by gbk** [comment]
@Jirapo @tommytroylin 这个是否跟新版修复的问题有关？看起来像是权限问题。

@WangYang-Rex 尝试把 `/Users/wy/.nowa-gui/` 删掉重启。

**Comment by Jirapo** [comment]
可以下载最新版

**Comment by WangYang-Rex** [comment]
把 /Users/wy/.nowa-gui/ 删掉，并安装最新版的是可以的
