### ISSUE TITLE
dingyou-dingtalk-mobile 模板不可用

### ISSUE THREAD

**Issue by HeartZhang** [nowa-webpack/nowa-gui#40]
不管是V2 还是V3 版本直接编译都报错
Error: Cannot find module 'webpack/lib/removeAndDo' 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15) 
at Function.Module._load (internal/modules/cjs/loader.js:520:25) 
at Module.require (internal/modules/cjs/loader.js:650:17) 
at require (internal/modules/cjs/helpers.js:20:18) 
at Object. (C:\Users\zhxin\.nowa\install\_extract-text-webpack-plugin@1.0.1@extract-text-webpack-plugin\ExtractedModule.js:30:42) 
at Module._compile (internal/modules/cjs/loader.js:702:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10) 
at Module.load (internal/modules/cjs/loader.js:612:32) 
at tryModuleLoad (internal/modules/cjs/loader.js:551:12) 
at Function.Module._load (internal/modules/cjs/loader.js:543:3) 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxx@1.0.0 build: `nowa build -e index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxxxx@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by gbk** [comment]
@HeartZhang 请按常见问题 1 处理：https://nowa-webpack.github.io/docs/chang_jian_wen_ti.html

**Comment by HeartZhang** [comment]
重新安装 nowa  一万多遍了 都是一样的问题

**Comment by Jirapo** [comment]
要删除用户目录下的nowa依赖

1。如果你使用的是命令行， rm -rf `npm root -g`/nowa-* ~/.nowa
https://nowa-webpack.github.io/docs/chang_jian_wen_ti.html

如果使用的是GUI，rm -rf ~/.nowa-gui./installation
https://nowa-webpack.github.io/nowa/qa.html
