### ISSUE TITLE
无法编译、启动项目了，很绝望

### ISSUE THREAD

**Issue by icoreman** [nowa-webpack/nowa-gui#43]
![image](https://user-images.githubusercontent.com/13469330/42452592-108bbfba-83bd-11e8-99e2-f8e3871d9d7d.png)
已经卸载重新安装了，nodejs/nowa gui，全都卸载过，新建一个模板，编译，报错。
很绝望。
下面是错误信息：
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Test@1.0.0~prebuild: Test@1.0.0
6 info lifecycle Test@1.0.0~build: Test@1.0.0
7 verbose lifecycle Test@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle Test@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Admin\NowaProject\Test\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Local\Programs\nowa-gui-version\resources\app\nodes;C:\Users\Admin\.nowa-gui\installation\node_modules\.bin;C:\Users\Admin\AppData\Local\Programs\nowa-gui-version\resources\app\node_modules\.bin;C:\Users\Admin\AppData\Roaming\npm;C:\Users\Admin\.nowa-gui\installation\node_modules\.bin;C:\Users\Admin\AppData\Local\Programs\nowa-gui-version\resources\app\nodes;C:\Users\Admin\AppData\Local\Programs\nowa-gui-version\resources\app\node_modules\.bin
9 verbose lifecycle Test@1.0.0~build: CWD: C:\Users\Admin\NowaProject\Test
10 silly lifecycle Test@1.0.0~build: Args: [ '/d /s /c', 'nowa build' ]
11 silly lifecycle Test@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle Test@1.0.0~build: Failed to exec build script
13 verbose stack Error: Test@1.0.0 build: `nowa build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid Test@1.0.0
15 verbose cwd C:\Users\Admin\NowaProject\Test
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
18 verbose node v10.5.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error Test@1.0.0 build: `nowa build`
22 error Exit status 1
23 error Failed at the Test@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by icoreman** [comment]
版本 1.9.7 win10 64位

**Comment by tommytroylin** [comment]
@icoreman 
https://github.com/nowa-webpack/nowa-gui/wiki/FAQ
请参考 nowa 找不到命令

**Comment by icoreman** [comment]
中文乱码，亲测可解决啊。
就是一个重置。
